# Generated by Django 4.2.7 on 2023-12-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_user_alter_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replys',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
