# Generated by Django 4.2.7 on 2023-12-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_options_category_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='badge',
            field=models.CharField(max_length=100, null=True, verbose_name='insignia'),
        ),
    ]
