# Generated by Django 4.2.7 on 2023-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0003_company_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('content', models.CharField(max_length=255, verbose_name='Contenido')),
                ('image', models.ImageField(default='null', upload_to='Experiencias', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('start_date', models.DateField(default='Fecha inicio', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default='Fecha final', verbose_name='Fecha de salida')),
                ('companies', models.ManyToManyField(blank=True, to='certificates.company', verbose_name='Empresas')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
            },
        ),
    ]
